[CmdletBinding()]param([string]$CandidateSha,[string]$RuntimeDirectory,[string]$ResultDirectory,[switch]$OperatorAuthorized)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
function Block([string]$c){Write-Output "preflight_result=BLOCKED check=$c";exit 1}
try{
 . (Join-Path $PSScriptRoot 'common.ps1');if(-not[OperatingSystem]::IsWindows()){Block 'windows_required'};if(-not$OperatorAuthorized){Block 'operator_authorization'};if($CandidateSha-cnotmatch'^[0-9a-f]{40}$'){Block 'candidate_sha'}
 $envs=[Environment]::GetEnvironmentVariables('Process');if(@($envs.Keys|Where-Object{[string]::Equals([string]$_,'COPILOT_CLI_PATH',[StringComparison]::OrdinalIgnoreCase)}).Count-ne0){Block 'copilot_cli_path'};if(-not$envs.Contains('CAO_ISSUE158_RUN_ID')-or([string]$envs['CAO_ISSUE158_RUN_ID'])-cnotmatch'^[0-9a-f]{32}$'){Block 'run_identity'};$runId=[string]$envs['CAO_ISSUE158_RUN_ID']
 foreach($n in @('pwsh','dotnet','git')){if($null-eq(Get-Command $n -ErrorAction SilentlyContinue)){Block 'prerequisite'}};$repo=Get-Issue158PhysicalPath (Join-Path $PSScriptRoot '..\..\..');foreach($f in @((Join-Path $PSScriptRoot 'common.ps1'),(Join-Path $PSScriptRoot 'scan-leaks.ps1'),(Join-Path $repo 'tests\CopilotAgentObservability.LocalMonitor.Tests\CopilotAgentObservability.LocalMonitor.Tests.csproj'))){if(-not(Test-Path -LiteralPath $f -PathType Leaf)){Block 'prerequisite'}}
 $head=(& git -C $repo rev-parse HEAD 2>$null|Out-String).Trim();if($LASTEXITCODE-ne0-or$head-cne$CandidateSha){Block 'candidate_mismatch'};$branch=(& git -C $repo symbolic-ref -q HEAD 2>$null|Out-String).Trim();if($LASTEXITCODE-eq0-or$branch){Block 'candidate_attached'};$dirty=(& git -C $repo status --porcelain=v1 --untracked-files=normal 2>$null|Out-String).Trim();if($LASTEXITCODE-ne0-or$dirty){Block 'candidate_dirty'}
 $runtime=Get-Issue158PhysicalPath $RuntimeDirectory;$result=Get-Issue158PhysicalPath $ResultDirectory;if((Get-Issue158LexicalPath $RuntimeDirectory)-cne$runtime-or(Get-Issue158LexicalPath $ResultDirectory)-cne$result){Block 'path_reparse'};$temp=Get-Issue158PhysicalPath ([IO.Path]::GetTempPath());if(-not(Test-Issue158Within $runtime $temp)-or-not(Test-Issue158Within $result $temp)){Block 'unsafe_path'};if($runtime-eq$result-or(Test-Issue158Within $runtime $result)-or(Test-Issue158Within $result $runtime)){Block 'path_alias'};if($repo-eq$runtime-or$repo-eq$result-or(Test-Issue158Within $repo $runtime)-or(Test-Issue158Within $repo $result)-or(Test-Issue158Within $runtime $repo)-or(Test-Issue158Within $result $repo)){Block 'repository_overlap'}
 if(@(Get-ChildItem -LiteralPath $runtime -Force).Count-ne1){Block 'runtime_owner'};if(@(Get-ChildItem -LiteralPath $result -Force).Count-ne1){Block 'result_owner'};try{[void](Get-Issue158Owner $runtime $runId $CandidateSha 'runtime' $runtime $result)}catch{Block 'runtime_owner'};try{[void](Get-Issue158Owner $result $runId $CandidateSha 'result' $runtime $result)}catch{Block 'result_owner'}
 try{$l=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,0);$l.Start();$l.Stop()}catch{Block 'loopback_bind'};Write-Output 'preflight_result=PASSED';exit 0
}catch{Block 'internal'}
