global using System.Globalization;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using Microsoft.Data.Sqlite;
global using CopilotAgentObservability.Telemetry;
global using CopilotAgentObservability.Persistence.Sqlite;
