using System.Globalization;
using System.Text.Json;

namespace CopilotAgentObservability.LocalMonitor;

internal static class ComparisonJson
{
    private static readonly (int Ordinal, string Key, string Label)[] Sections = [(1, "target", "対象"), (2, "tokens", "トークン"), (3, "input_token_breakdown", "入力トークンの内訳"), (4, "time_and_execution", "時間・実行量"), (5, "skills", "スキル"), (6, "tools", "ツール"), (7, "subagents", "サブエージェント"), (8, "errors_and_retries", "エラー・再試行"), (9, "conditions", "比較条件")];
    internal static byte[] Preview(LocalComparisonProjectionPreview x) => Write(j => { j.WriteStartObject(); j.WriteString("schema_version", "local-monitor-comparison-preview.response.v1"); j.WriteBoolean("valid", x.Valid); j.WriteString("selection_sha256", x.SelectionSha256); j.WriteString("preview_revision", x.PreviewRevision); j.WritePropertyName("cohorts"); j.WriteStartObject(); C("a", "基準"); C("b", "比較対象"); j.WriteEndObject(); j.WritePropertyName("requested"); j.WriteStartArray(); foreach (var v in x.Requested) { j.WriteStartObject(); j.WriteString("cohort", v.Cohort); j.WriteNumber("request_ordinal", v.RequestOrdinal); j.WriteString("session_id", v.SessionId); j.WriteEndObject(); } j.WriteEndArray(); j.WritePropertyName("included"); j.WriteStartArray(); foreach (var v in x.Included) { j.WriteStartObject(); j.WriteString("cohort", x.Requested.First(r => r.SessionId == v.SessionId).Cohort); j.WriteString("session_id", v.SessionId); j.WritePropertyName("metadata"); j.WriteStartObject(); j.WriteString("archive_state", v.ArchiveState); j.WriteString("source", v.Sources.FirstOrDefault() ?? "unknown"); j.WriteString("model", v.Models.FirstOrDefault() ?? "unknown"); j.WriteNumber("projection_version", v.ProjectionVersion); j.WriteString("completeness", v.Completeness); j.WritePropertyName("metric_coverage"); j.WriteStartArray(); foreach (var m in v.MetricCoverage) j.WriteStringValue(m); j.WriteEndArray(); j.WriteNumber("session_revision", v.SessionRevision); j.WriteString("projection_revision", v.ProjectionRevision); j.WriteEndObject(); j.WriteEndObject(); } j.WriteEndArray(); j.WritePropertyName("excluded"); j.WriteStartArray(); foreach (var v in x.Excluded) { j.WriteStartObject(); j.WriteString("cohort", v.Cohort); j.WriteNumber("request_ordinal", v.RequestOrdinal); j.WriteString("session_id", v.SessionId); j.WriteString("reason", v.Reason); j.WriteNull("metadata"); j.WriteEndObject(); } j.WriteEndArray(); j.WriteEndObject(); void C(string c, string label) { j.WritePropertyName(c); j.WriteStartObject(); j.WriteString("label", label); j.WriteNumber("requested_count", x.Requested.Count(v => v.Cohort == c)); j.WriteNumber("included_count", x.Included.Count(v => x.Requested.Any(r => r.Cohort == c && r.SessionId == v.SessionId))); j.WriteNumber("excluded_count", x.Excluded.Count(v => v.Cohort == c)); j.WriteEndObject(); } });
    internal static byte[] Create(LocalComparisonSnapshotWrite x, string location) => Write(j => { j.WriteStartObject(); j.WriteString("schema_version", "local-monitor-comparison-create.response.v1"); j.WriteString("comparison_id", x.ComparisonId); j.WriteString("location", location); j.WriteString("receipt_sha256", x.Results[0].PayloadSha256); j.WriteString("created_at", Time(x.CreatedAt)); j.WriteString("expires_at", Time(x.ExpiresAt)); j.WriteEndObject(); });
    internal static byte[] Read(LocalComparisonFrozenSnapshot x) => Write(j => { j.WriteStartObject(); j.WriteString("schema_version", "local-monitor-comparison-read.response.v1"); j.WriteString("comparison_id", x.ComparisonId); j.WriteString("repository_id", x.RepositoryId); j.WriteString("receipt_sha256", x.Results[0].PayloadSha256); j.WriteString("created_at", Time(x.CreatedAt)); j.WriteString("expires_at", Time(x.ExpiresAt)); j.WritePropertyName("cohorts"); j.WriteStartObject(); C("a", "基準"); C("b", "比較対象"); j.WriteEndObject(); j.WritePropertyName("sections"); j.WriteStartArray(); foreach (var s in Sections) { j.WriteStartObject(); j.WriteNumber("ordinal", s.Ordinal); j.WriteString("key", s.Key); j.WriteString("label", s.Label); j.WriteEndObject(); } j.WriteEndArray(); j.WritePropertyName("results"); j.WriteStartArray(); foreach (var r in x.Results.Where(r => r.ResultOrdinal > 0 && r.RowKind is not ("skill" or "tool" or "subagent"))) { j.WriteStartObject(); j.WriteNumber("result_ordinal", r.ResultOrdinal); j.WriteString("section_key", Sections[r.SectionOrdinal - 1].Key); j.WriteString("row_kind", "scalar"); j.WriteString("row_key", r.RowKey); Values(j, r.Values); j.WriteEndObject(); } j.WriteEndArray(); j.WriteEndObject(); void C(string c, string label) { var ids = x.Memberships.Where(m => m.Cohort == c).OrderBy(m => m.Ordinal).Select(m => m.SessionId).ToArray(); j.WritePropertyName(c); j.WriteStartObject(); j.WriteString("label", label); j.WritePropertyName("session_ids"); j.WriteStartArray(); foreach (var id in ids) j.WriteStringValue(id); j.WriteEndArray(); j.WriteNumber("included_count", ids.Length); j.WriteEndObject(); } });
    internal static byte[] Rows(string id, string family, IReadOnlyList<LocalComparisonStoredResult> rows, string? next) => Write(j => { j.WriteStartObject(); j.WriteString("schema_version", "local-monitor-comparison-rows.response.v1"); j.WriteString("comparison_id", id); j.WriteString("family", family); j.WritePropertyName("items"); j.WriteStartArray(); foreach (var r in rows) { j.WriteStartObject(); j.WriteNumber("result_ordinal", r.ResultOrdinal); j.WriteString("row_key", r.RowKey); j.WriteString("display_name", r.Values.First(v => v.Key == "display_name").Value); Values(j, r.Values.Where(v => v.Key is not ("display_name" or "sort_key"))); j.WriteEndObject(); } j.WriteEndArray(); Nullable(j, "next_cursor", next); j.WriteEndObject(); });
    internal static byte[] Evidence(string id, int ordinal, string? field, IReadOnlyList<LocalComparisonStoredEvidence> items, string? next) => Write(j => { j.WriteStartObject(); j.WriteString("schema_version", "local-monitor-comparison-evidence.response.v1"); j.WriteString("comparison_id", id); j.WriteNumber("result_ordinal", ordinal); Nullable(j, "field_key", field); j.WritePropertyName("items"); j.WriteStartArray(); foreach (var x in items) { var included = x.AvailabilityState is "recorded" or "explicit_zero"; j.WriteStartObject(); j.WriteNumber("evidence_ordinal", x.EvidenceOrdinal + 1); j.WriteString("cohort", x.Cohort); j.WriteString("session_id", x.SessionId); j.WriteString("state", included ? "included" : "unavailable"); Nullable(j, "unavailable_reason", included ? null : Unavailable(x.AvailabilityState)); j.WriteNull("consumed_value"); Nullable(j, "consumed_revision", x.RevisionSha256); var execution = x.SourceKind == "workspace_execution" ? x.SourceIdentity : null; var node = x.SourceKind == "workspace_node" ? x.SourceIdentity : null; Nullable(j, "execution_id", execution); Nullable(j, "node_id", node); j.WriteString("session_location", $"/sessions/{x.SessionId}"); j.WriteEndObject(); } j.WriteEndArray(); Nullable(j, "next_cursor", next); j.WriteEndObject(); });
    private static string Unavailable(string x) => x is "not_observed" or "source_unsupported" or "capture_gap" or "certification_pending" ? x : "projection_unavailable";
    private static void Values(Utf8JsonWriter j, IEnumerable<KeyValuePair<string, string>> values) { j.WritePropertyName("values"); j.WriteStartArray(); foreach (var v in values) { j.WriteStartObject(); j.WriteString("key", v.Key); j.WriteString("value", v.Value); j.WriteEndObject(); } j.WriteEndArray(); }
    private static void Nullable(Utf8JsonWriter j, string name, string? value) { if (value is null) j.WriteNull(name); else j.WriteString(name, value); }
    private static string Time(DateTimeOffset x) => x.ToUniversalTime().ToString("O", CultureInfo.InvariantCulture);
    private static byte[] Write(Action<Utf8JsonWriter> action) { using var stream = new MemoryStream(); using (var j = new Utf8JsonWriter(stream, new JsonWriterOptions { Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping })) action(j); return stream.ToArray(); }
}
